### ISSUE TITLE
Undefined functions，running error

### ISSUE THREAD

**Issue by hejunqing** [Cyril-JZ/InteR#1]
Hi bro, I download the data and ran your code, then got Error：load_tsv undefined！ Since we don't know the format of output， could you add the definition？Thanks

**Comment by Cyril-JZ** [comment]
Thx for your attention! 
Did you put the downloaded tsv file into `./data_msmarco/` and rename it as `collection.tsv` correctly?
Besides, the function `load_tsv` is defined in `utils.py`.
BTW could you share more info about the error messages?

**Comment by SYKKKKKKKKKKK** [comment]
您好，我无法正确解压contriever_msmarco_index.tar.gz文件，在服务器中解压报错为：
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

看起来像是我没有正确下载目标源文件，是吗？

**Comment by Cyril-JZ** [comment]
> 您好，我无法正确解压contriever_msmarco_index.tar.gz文件，在服务器中解压报错为： gzip: stdin: unexpected end of file tar: Unexpected EOF in archive tar: Unexpected EOF in archive tar: Error is not recoverable: exiting now
> 
> 看起来像是我没有正确下载目标源文件，是吗？

Yes, I think so too.
