### ISSUE TITLE
未能正确解压 contriever_msmarco_index.tar.gz 文件

### ISSUE THREAD

**Issue by SYKKKKKKKKKKK** [Cyril-JZ/InteR#2]
您好，我未能在服务器中正确解压contriever_msmarco_index.tar.gz文件，并报错为：
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

下载的源文件大小为23.4G

请问解压失败是什么原因呢？

**Comment by Cyril-JZ** [comment]
Hello~看起来是下载不完整。您再试试？

**Comment by SYKKKKKKKKKKK** [comment]
下午好，那我再试试吧，国内环境拉取dropbox文件，还挺困难

**Comment by SYKKKKKKKKKKK** [comment]
可以加您一个联系方式吗，邮箱即可

**Comment by Cyril-JZ** [comment]
Sure! fengjiazhan@pku.edu.cn

**Comment by 1204120** [comment]
> Hello~看起来是下载不完整。您再试试？

哈喽，想问下你最后解压成功了吗，我也是遇到相同的问题

**Comment by atailab** [comment]
你好请问您解决了文件问题吗，我在下载该文件时总是中断，可以提供网盘的下载链接吗万分感谢

**Comment by LiBingbingg** [comment]
你好，我最近也在尝试复现hyde，contriever_msmarco_index.tar.gz文件也是下载不全，使用浏览器和下载器下载最后都没有成功，请问您最后解决了吗？

**Comment by LiBingbingg** [comment]
> > Hello~看起来是下载不完整。您再试试？
> 
> 哈喽，想问下你最后解压成功了吗，我也是遇到相同的问题

您好，请问你能成功下载contriever_msmarco_index.tar.gz文件吗？我使用命令、浏览器和下载器下载都没有成功，不知道还有什么别的解决办法？

**Comment by Cyril-JZ** [comment]
>  你好，我最近也在尝试复现hyde，contriever_msmarco_index.tar.gz文件也是下载不全，使用浏览器和下载器下载最后都没有成功，请问您最后解决了吗？

Hi @LiBingbingg, these are the OneDrive urls. You can have a try [code: inter2024]
- https://1drv.ms/u/c/1310d6f5873b5c46/EdrDvkAmT4pDk7oaMsm-i6cBJ9vv9_g-w5O8E7tdpifaEQ?e=5GB55Y
- https://1drv.ms/f/c/1310d6f5873b5c46/ElqYuHzqp3VCgIiuhy-nZawBJ8-pJ_ft3NUYxSU4pcC1ZA?e=X9FWDp

**Comment by ZXMJ** [comment]
@Cyril-JZ 您好，这个OneDrive文件需要密码，能否提供一下

**Comment by Cyril-JZ** [comment]
> [code: inter2024]

在这里~
